name: Branch Build gradle publish
on:
  push:
    branches:
    - OES-1.30.x-master-adhoc
  
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  publish-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build
        env:
          NEXUS_VERSION: 1-0-SNAPSHOT
        run: |
            
              cat <<EOF>> patch
              
              version = "$NEXUS_VERSION"
              group = 'io.spinnaker.gradle'
              apply plugin: 'maven-publish'

              publishing{
                   publications{
                       maven(MavenPublication){
                            groupId = 'io.spinnaker.gradle'
                            artifactId = 'NEXUSARTIID'
                            version = "$NEXUS_VERSION"
                            from components.java
                 pom {
                   name = 'NEXUSARTIID'
                   description = 'A description of my library'
                   }
                 }
              }

              repositories {
                 maven{
                 name = 'nexus'
                 url "https://nexus.opsmx.net/repository/maven-snapshots/"
                  credentials {
                    username = "${{ secrets.NEXUS_USERNAME }}"
                    password = "${{ secrets.NEXUS_PASSWORD }}"
                         }
                     }
                }
               }  
                               tasks.withType(GenerateModuleMetadata).configureEach {
                                         suppressedValidationErrors.add('enforced-platform')
                                       }

              EOF
             
              ls -d */  | grep "spinnaker\-project\-plugin" | sed 's/\///g' > ds.txt
              
              for i in $(cat ds.txt) 
              do
               sed  s/NEXUSARTIID/$i/g patch > patchnew
               cat patchnew >> $i/build.gradle
             
              done
              
                # sed  s/NEXUSARTIID/spinnaker-extensions/g patch > patchnew
               #cat patchnew >> spinnaker-extensions/build.gradle.kts
              
                ./gradlew --no-daemon -PenableCrossCompilerPlugin=true  publish -x test
